### ISSUE TITLE
Review the API

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/gpsea#133]
We want to make using Genophenocorr as simple as possible.

There are several things that can be done:
- create helper functions that need just the most basic input, while letting the user tweak the details, if desired
- show examples in the documentation and in the notebooks
- use meaningful function names, and informative pydoc strings, related to #59, #111

We need to review the API when the functionality is finished and we are ready to publish the paper, along with `v1.0.0`.

@graefea can help with the review.

**Comment by ielis** [comment]
@graefea I'm adding you here, but please wait with the actual review until we are done with the development. We will keep you updated.

**Comment by aslgraefe** [comment]
@ielis @pnrobinson @lnrekerle I am activating this issue to start commenting on the gpsea documentation.

**Comment by aslgraefe** [comment]
**Comments on the Documentation**

**Minor Comments**
- _Tutorial_: move the Note below into the section _Show cohort summary_
´´´
IPython.display import HTML, display
display(HTML(report))
´´´

**Comment by ielis** [comment]
@aslgraefe 

regarding your comment on
> create helper functions that need just the most basic input, while letting the user tweak the details, if desired 

I am not planning to make any major updates to the workflow at this point and we will expect the users to follow the examples from the docs, as I said yesterday. There is more to the analysis than what is in the examples, and I am not sure if it can be simplified even further without losing the "generality".

Regarding the other comments from your post, I think we went through them yesterday. However, please let me know if this is not what you think and if you expect more feedback.

Thank you very much! :)

**Comment by ielis** [comment]
Yeah, I think so, let me close!
