### ISSUE TITLE
PLA2G6 - correlations

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/gpsea#152]
https://ojrd.biomedcentral.com/articles/10.1186/s13023-023-02780-9#Tab3

**Comment by pnrobinson** [comment]
moving to https://github.com/monarch-initiative/phenopacket-store/issues/118

**Comment by ielis** [comment]
@pnrobinson if you don't mind, I will keep this issue around to keep track an example of a reported GP correlation.

**Comment by pnrobinson** [comment]
After looking at the publication, there was not sufficient shared information to make it a good idea to do this analysis. I think we have more than enough examples now anyway.
