### ISSUE TITLE
Simplify AR predicate

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/gpsea#284]
The AR predicate is exhaustive in terms of produced categorizations: `HOM_REF`, `HET`, and `BIALLELIC_ALT`.

In practice, however, it is not so useful to differentiate between `HOM_REF` and `HET`. Therefore, the predicate should be simplified to categorize the individuals into 2 categories only:

- `HOM_REF`, `HET`
- `BIALLELIC_ALT`

**Comment by pnrobinson** [comment]
Please let's not use HOM_REF, because in our intended use case we are not comparing to REF, we are comparing to other variants. I think it would be better to require users to name the categories to avoid confusion!
