### ISSUE TITLE
Promoter variants

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/gpsea#291]
https://github.com/monarch-initiative/gpsea/pull/289

Add more information to the Promoter variant

**Comment by pnrobinson** [comment]
@ielis 
We are currently not recognizing promoter variants -- 2KB_upstream_variant, GPSEA is trying to parse as a SV, and throws an error.
Can we discuss the best way to fix?

**Comment by ielis** [comment]
Let's discuss today!

**Comment by pnrobinson** [comment]
I have refactored this class in pyphetools to add VCF information, it is now called IntergenicVariant. With this, GPSEA can ingest these variants. Closing this issue.
