### ISSUE TITLE
box plot for t test

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/gpsea#311]
The following code leads to an error
```
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(5, 3))
result_1_or_2_missense_17hp.plot_boxplots(gt_predicate=result_1_or_2_missense_17hp, ax=ax)
```
i.e.,
```

'PhenotypeScoreAnalysisResult' object has no attribute 'get_categories'
```

Also, we need to remove NaN values before plotting, I think.

See https://github.com/monarch-initiative/gpsea-cs/blob/develop/notebooks/CYP21A2/CYP21A2_gpsea.ipynb
for possible styling -- we could add this to the documentation for instance, but right now the basic plot does not work.
Everything is still a bit WiP, but this example is giving us a significant result.

**Comment by ielis** [comment]
`result_1_or_2_missense_17hp` seems to be of the `PhenotypeScoreAnalysisResult` type. However, the function needs a GenotypePolyPredicate (`gt_predicate`), as indicated in the [API docs](https://monarch-initiative.github.io/gpsea/stable/apidocs/gpsea.analysis.pscore.html#gpsea.analysis.pscore.PhenotypeScoreAnalysisResult.plot_boxplots). So, this one should be easy to fix.

Regarding NaNs, yes, we may need to remove the NaNs before plotting. The internet says that boxes for columns/datasets with NaN values will not be plotted.

Regarding styling, I do not want to go overboard here. Remember, the user is in control of the `ax` object, which can be styled to user's heart delight.
