### ISSUE TITLE
default arguments for MTC filter

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/gpsea#312]
I think we should use a default argument for the MTF filter of 40% for both the genotype and the annotation filters.
This is because if we always show the argument, then we will tempt people to change it and try again, which will lead to lots of implicit multiple testing that will not get corrected for. We should run all of the cases in this first analysis just using the default settings. If there is a true reason for changing it, people can read about it in the documentation and will be educated on why it is bad to try things with many different settings!
For now I think that 40% is a good compromise overall.
@ielis Thoughts?

**Comment by ielis** [comment]
I concur on using the default value in our analyses and, therefore, simplifying the code, docs, and `gpsea-cs` notebooks.

I have no feelings about 40%, perhaps it sounds a bit stringent, but it is reasonable in the context of an ontology-driven analysis.
