### ISSUE TITLE
BRD4 cohort potential problem?

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/gpsea#340]
When I load the NIPBL cohort, there are 22 phenopackets, but only 18 individuals get loaded. Yet there is no error warning. Can we take a closer look?
```
Loaded 22 phenopackets (NIPBL).
Individuals Processed: 100%|██████████| 22/22 [00:00<00:00, 380.69individuals/s]
Loaded 18 individuals
Validated under permissive policy
No errors or warnings were found
```

**Comment by ielis** [comment]
_NIPBL_ loaded and validated OK on my end, so this is probably a mismatch of cohorts (_NIPBL_ -  22 individuals, _BRD4_ - 18 individuals as of Phenopacket Store 0.1.21).

Let's reopen if the issue shows up again...
