### ISSUE TITLE
SUOX cohort problem

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/gpsea#341]
In this cohort, the variant effects are not being created. No error warning is emitted. I am unsure of what is going on.

https://github.com/monarch-initiative/gpsea-cs/blob/develop/notebooks/SUOX/SUOX_gpsea.ipynb

**Comment by ielis** [comment]
@pnrobinson There seems to be an error in 2nd cell. Can you please verify if the `gene_symbol` is correct?

Otherwise, after fixing the symbol and ingesting the *SUOX* cohort from Phenopacket Store 0.1.22, the cohort looks reasonable.
