### ISSUE TITLE
SIMPLIFICATION

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/gpsea#343]
@ielis 
We are adding all of this code to each notebook, but it would be less error prone if we simplified it by assuming defaults
```python
from gpsea.analysis.predicate.phenotype import prepare_predicates_for_terms_of_interest
from gpsea.analysis.mtc_filter import HpoMtcFilter
from gpsea.analysis.pcats.stats import FisherExactTest
from gpsea.analysis.pcats import HpoTermAnalysis

pheno_predicates = prepare_predicates_for_terms_of_interest(
    cohort=cohort,
    hpo=hpo,
)

mtc_filter = HpoMtcFilter.default_filter(hpo)
mtc_correction = 'fdr_bh'
mtc_alpha = 0.05

count_statistic = FisherExactTest()

analysis = HpoTermAnalysis(
    count_statistic=count_statistic,
    mtc_filter=mtc_filter,
    mtc_correction=mtc_correction,
    mtc_alpha=mtc_alpha,
)
```
This could easily be simplified to 
```python
from gpsea.analysis.pcats import HpoTermFteAnalysis

analysis = HpoTermFteAnalysis(
     cohort=cohort,
     hpo=hpo,
)
```

This is because it would almost always be a mistake to use other settings for this analysis that people will be using every single time! **HpoTermFteAnalysis** is either a new class that has these defaults or it is renamed from the existing class, whose name is too general.

**Comment by ielis** [comment]
Sounds good but I'll do it in a slightly different way.

There will be a function for getting `HpoTermAnalysis` with the default parameters:

```python
from gpsea.analysis.pcats import configure_hpo_term_analysis

analysis = configure_hpo_term_analysis(hpo)
```

This can, in principle, be done for other analyses as well.

**Comment by pnrobinson** [comment]
+1
