### ISSUE TITLE
"Zinc finger"

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/gpsea#344]
The protein display is not showing domains of type "Zinc finger", 
example ZFX 

https://www.uniprot.org/uniprotkb/P17010/entry#family_and_domains

@ielis 
We can consider throwing an error if there is a domain that we do not recognize, but I think in the early stages of this class we incorrectly assumed that there would be just a small number of domain types. At the very least we need to show the user there was a problem. I will add this for now.

**Comment by ielis** [comment]
Sounds good.

**Comment by ielis** [comment]
Fixed by #346
