### ISSUE TITLE
gene2transcripts error for POLR1A

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/gpsea#364]
I am using the following call to request information about POLR1A
```
https://rest.variantvalidator.org/VariantValidator/tools/gene2transcripts/NM_015425.6
```
It returns this message
```
{
  "error": "Unable to recognise gene symbol LOC90784",
  "requested_symbol": "NM_015425.6"
}
```
I think this is a bug in VV and have reported this. However, we are unable to analyze POLR1A. Possibly we should make a backup manual method for cases like this?

**Comment by pnrobinson** [comment]
The VV team responded and will fix soon

**Comment by ielis** [comment]
This may have already been fixed, since _POLR1A_ ingest from Phenopacket Store `v0.1.21` finished with no issues on my machine today.

This may be related to #275 , and the Variant Validator fix may have killed :bird: :bird: with just one :rock:
