### ISSUE TITLE
Consider adding a step for inferring excluded features for a cohort

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/gpsea#48]
Consider adding a step into the `Cohort` ETL pipeline that will infer exclusion of a phenotypic feature if not explicitly present in the phenopacket.

The inference must account for the other phenotypic features of the patient to ensure no logical inconsistencies are introduced.

**Comment by lnrekerle** [comment]
Is this covered in the Heuristic Strategy? Or could it be added to it? 
@pnrobinson @ielis

**Comment by ielis** [comment]
No, it is not, but this is a low-priority, in my opinion. Let's leave it for now.

**Comment by pnrobinson** [comment]
We now have this, it is probably not a function that should be used by default, but it works.
